apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-user
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: udaragram-feed-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-feed
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-reverse-proxy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-reverse-proxy
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-frontend
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
